### ISSUE TITLE
Rate limiting is broken

### ISSUE THREAD

**Issue by jedis00** [abbydiode/UndiscordPlus#2]
Hello,

I tried this version of the fork and it's completely broken once you've been rated limited. I can't copy the text out of the window to share it here, but it says:

```
Being rate limited by the API! Adjusted delay to 83ms.
Delete delay: 83ms
Cooling down for 83ms.
Deleting...
Being rate limited by the API! Adjusted delay to 83ms.
Delete delay: 83ms
Cooling down for 83ms.
Deleting...
Being rate limited by the API! Adjusted delay to 83ms.
Delete delay: 83ms
Cooling down for 83ms.
Deleting...
Being rate limited by the API! Adjusted delay to 83ms.
Delete delay: 83ms
Cooling down for 83ms.
Deleting...
Being rate limited by the API! Adjusted delay to 83ms.
Delete delay: 83ms
Cooling down for 83ms.
Deleting...```

**Comment by Toby222** [comment]
Seems like it's reading the Retry-After as [milliseconds](https://github.com/abbydiode/UndiscordPlus/blob/e696ba8b5944132ea0cdec7ce90d537878941d64/UndiscordPlus.user.js#L102) instead of [seconds](https://discord.com/developers/docs/topics/rate-limits#exceeding-a-rate-limit-rate-limit-response-structure).

**Comment by jedis00** [comment]
Yeah the official one works correctly, but it gets rate limited by the API and the delay seems to be arbitrarily too long, as I can delete more before its cooldown has elapsed. It gives an estimated time of half a day to delete 22k messages. But the rate limiting will make it take half a year at this point.

**Comment by batu-0** [comment]
I've had this issue as well, except I think I figured out the reason why. The fork isn't broken, this happens because the original version of the script uses API v6 but this fork has been updated to API v9 for compatibility with threads, and apparently Discord decided to change the rate-limiting behavior on the recent API versions, possibly to detect self-bots. This problem can be solved by the implementation of a cooldown mecanism that doesn't fully rely on Discord's rate-limiting requests. However, there's more. According to my testing, if the delays aren't randomized slightly, Discord also seems to detect that (after like 80~ messages deleted) and prevent the deletion of more messages until you manually stop the script, wait like 15 seconds and start it again.

**Comment by batu-0** [comment]
> Seems like it's reading the Retry-After as [milliseconds](https://github.com/abbydiode/UndiscordPlus/blob/e696ba8b5944132ea0cdec7ce90d537878941d64/UndiscordPlus.user.js#L102) instead of [seconds](https://discord.com/developers/docs/topics/rate-limits#exceeding-a-rate-limit-rate-limit-response-structure).

This is the reason, but I still suggesst offsetting the cooldown and deletion delays by a random amount of time between 120 and 300 ms so it'd be a bit harder to detect.

**Comment by abbydiode** [comment]
This fork introduced an upgrade to the V9 API, I suppose that must've caused this since nothing else about the the way delays are handled was changed.

**Comment by abbydiode** [comment]
Just implemented a fix and tested it myself, works fine for me again! Thanks!
